module.exports = {
    mode: 'jit',
    purge: [
        './pages/**/*.{js,ts,jsx,tsx}',
        './components/**/*.{js,ts,jsx,tsx}',
    ],
    darkMode: 'class', // or 'media' or 'class'
    theme: {
        extend: {
            background: {
                'primary': '#f00'
            },
            boxShadow: {
                'offset-black': '2px 2px black',
                '-offset-black': '-2px -2px black',
                'offset-red': '2px 2px red',
                '-offset-red': '-2px -2px red',
                'offset-orange': '2px 2px orange',
                '-offset-orange': '-2px -2px orange',
                'offset-yellow': '2px 2px yellow',
                '-offset-yellow': '-2px -2px yellow',
                'offset-lightgreen': '2px 2px lightgreen',
                '-offset-lightgreen': '-2px -2px lightgreen',
                'offset-darkgreen': '2px 2px darkgreen',
                '-offset-darkgreen': '-2px -2px darkgreen',
                'offset-cyan': '2px 2px cyan',
                '-offset-cyan': '-2px -2px cyan',
                'offset-lightblue': '2px 2px lightblue',
                '-offset-lightblue': '-2px -2px lightblue',
                'offset-darkblue': '2px 2px darkblue',
                '-offset-darkblue': '-2px -2px darkblue',
                'offset-indigo': '2px 2px indigo',
                '-offset-indigo': '-2px -2px indigo',
                'offset-purple': '2px 2px purple',
                '-offset-purple': '-2px -2px purple',
                'offset-white': '2px 2px white',
                '-offset-white': '-2px -2px white',

                'offset-active-black': '5px 5px black',
                '-offset-active-black': '-5px -5px black',
                'offset-active-red': '5px 5px red',
                '-offset-active-red': '-5px -5px red',
                'offset-active-orange': '5px 5px orange',
                '-offset-active-orange': '-5px -5px orange',
                'offset-active-yellow': '5px 5px yellow',
                '-offset-active-yellow': '-5px -5px yellow',
                'offset-active-lightgreen': '5px 5px lightgreen',
                '-offset-active-lightgreen': '-5px -5px lightgreen',
                'offset-active-darkgreen': '5px 5px darkgreen',
                '-offset-active-darkgreen': '-5px -5px darkgreen',
                'offset-active-cyan': '5px 5px cyan',
                '-offset-active-cyan': '-5px -5px cyan',
                'offset-active-lightblue': '5px 5px lightblue',
                '-offset-active-lightblue': '-5px -5px lightblue',
                'offset-active-darkblue': '5px 5px darkblue',
                '-offset-active-darkblue': '-5px -5px darkblue',
                'offset-active-indigo': '5px 5px indigo',
                '-offset-active-indigo': '-5px -5px indigo',
                'offset-active-purple': '5px 5px purple',
                '-offset-active-purple': '-5px -5px purple',
                'offset-active-white': '5px 5px white',
                '-offset-active-white': '-5px -5px white',
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
